# dev-us
spring:
  main:
    banner-mode: off

server:
  port: 9095
  servlet:
    session:
      timeout: 1m
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: pa55wd
    key-store-type: pkcs12
    key-alias: springboot
    key-password: pa55wd
#  port: 8443

logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    com.vht: DEBUG
