# dev-us
spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: https://sentinel-rhsso-dev-eu.desktop-preprod.qa.aws.private.inf0.net/auth/realms/demo
        registration:
          keycloak-client:
            provider: keycloak-provider
            client-id: sbpep
            client-secret: d01dde63-46a5-4476-9a60-584e87a38837
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: https://sentinel-rhsso-dev-eu.desktop-preprod.qa.aws.private.inf0.net/auth/realms/demo/protocol/openid-connect/certs
