# dev-us
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: https://sso.qa.platform.refinitiv.com/auth/realms/ciam
        registration:
          keycloak-client:
            provider: keycloak-provider
            client-id: sbpep
            client-secret: 577f018d-3c54-4411-93f1-645b58e67c44
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: https://sso.qa.platform.refinitiv.com/auth/realms/ciam/protocol/openid-connect/certs
